image: fedora:rawhide

variables:
  DEPENDENCIES: glib2-devel libgudev-devel gtk-doc intltool autoconf automake
                gcc gcc-c++ glibc-devel make

build:
  before_script:
    - dnf update -y --nogpgcheck && dnf install -y --nogpgcheck $DEPENDENCIES
  script:
    - ./autogen.sh --disable-dependency-tracking
    - make
    - make install
    - make distcheck
