image: fedora:rawhide

variables:
  DEPENDENCIES: glib2-devel
                libgudev-devel
                gtk-doc
                gcc
                gcc-c++
                glibc-devel
                meson
                git
                libxslt

build:
  before_script:
    - dnf update -y --nogpgcheck && dnf install -y --nogpgcheck $DEPENDENCIES
  script:
    - meson -Dgtk_doc=true _build
    - ninja -v -C _build
    - ninja -v -C _build switcheroo-control-doc
    - ninja -v -C _build install
    - ninja -v -C _build uninstall
    - ninja -v -C _build dist
